### ISSUE TITLE
Missing DLLs when opening release EXE

### ISSUE THREAD

**Issue by BartolJukica** [Avi225/particle_simulation#2]
When opening the EXE it returns an error saying `libgcc_s_seh-1.dll` and `libstdc++-6.dll` are missing.

It appears like some development binaries are missing from the system (maybe like Visual C++ or something similar).

**Comment by Avi225** [comment]
It's an issue with the release, the build did not include `-static-libgcc` and `-static-libstdc++`, new releases will include these two static libraries.
